version: '3.7'
services:
  elm:
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    volumes:
      - .:/app
    command: init
    ports:
      - 8080:8080