version: '3.7'
services:
  elm:
    build:
      context: .
      args:
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
    environment:
      - "http_proxy=${http_proxy}"
      - "https_proxy=${https_proxy}"
      - "no_proxy=127.0.0.1,localhost,192.168.2.0/24"
    volumes:
      - .:/code
    working_dir: /code
    command: //bin/sh
    ports:
      - 8000:8000
    tty: true